config/routes.rb
Fishplate::Application.routes.draw do
  
  scope :controller => :mains do
    get 'index'
    get 'about'
    get 'portfolio'
    get 'creative_minds'
    

  end

  


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'mains#index'

  # See how all your routes lay out with "rake routes"

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/message.rb
class Message 
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming



  attr_accessor :name, :email, :mobile, :reason, :comment
 
  validates_presence_of :name, :message => "Don't forget your name"
  validates_presence_of :reason, :message => "Please Select"
  validates_numericality_of :mobile, :message => "Is that right?"

  #validates_uniqueness_of :email  
 
  validates :name, :email, :mobile, :reason, :comment, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end


  def persisted?
    false
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

def new
  @message = Message.new
end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to root_path, :notice => "Message was successfully sent."
    else
      flash.now.alert = "Please fill all fields."
      render :action => 'new'
    end
  end



end

app/controllers/mains_controller.rb
class MainsController < ApplicationController

def index

end

def about

end

def portfolio

end


def creative_minds

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/contact/new.html.erb
<div class="container">
  <div class="row">
    <div class="span12 minus65">
      <h1 class="titles">making contact</h1>
      <h3 class="smalltitles minus20">not in the E.T sense</h3>
    </div>
  </div>
</div>





<div class="container map">
  <div class="row">
    <div class="span6 offset3 thickborder">
      <%= form_for @message, :url => contact_path, :multipart => true, :validate => true do |f| %>
  
      <%= f.label :name, "Your Name" %>
      <%= f.text_field :name  %>
    
       <div class="border-top"></div>

      <%= f.label :email, "Email Address" %>
      <%= f.text_field :email %>
      <div class="border-top"></div>
   
      <%= f.label :mobile, "Phone Number" %>
      <%= f.text_field :mobile %>
      <div class="border-top"></div>
   
      <%= f.label :reason, "I'm Interested In"%>
      <%= f.select :reason, [['Web Design'],['Branding'],['Apps'], ['Other']], {:include_blank => 'Please Select'} %>
      <div class="border-top"></div>
  
      <%= f.label :comment, "Questions or Comments", :id => "commentlabel" %><br>
      <%= f.text_area :comment, :size=> "60x10", :id => "formcomment" %><br>
 
      <%= f.submit "Send" %>
  
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag %>
  <title>Fishplate Studios</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
</head>
<body>
  <div class="container">

  <div class="container">
    <div class="row">
      <div class="span12">
        <header>
          <img src="/assets/logo.png" alt="Fishplate Studios">
        </header>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span12">
        <nav class="navbar">
          <ul>
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'About FP Studios', about_path %></li>
            <li><%= link_to 'Portfolio', portfolio_path %></li>
            <li><%= link_to 'Creative Minds', creative_minds_path %></li>
            <li><%= link_to 'Contact Us', contact_path %></li>
          </ul>
        </nav>

  <div id="responsiveNav">
    <nav>
      <select id="respn">
       <option value="/index">Home</option>
       <option value="/about">About Fp Studios</option>
       <option value="/portfolio">Portfolio</option>
       <option value="/creative_minds">Creative Minds</option>
       <option value="/contact">Contact Us</option>
      </select>
    </nav>
   </div><!--/responsiveNav-->
      </div>
    </div>
  </div>

<%= yield %>
<%= render 'shared/footer' %>
</div><!--/container-->


<script type="text/javascript">
$('#respn').change(function(){
    var url = $(this).val();
    window.location = url;
});

</script>
</body>
</html>

app/views/mains/about.html.erb
<div class="container">
  <div class="row">
    <div class="span12 minus65">
     <h1 class="titles">about FP Studios</h1>
    <h3 class="smalltitles minus20">you are curious then?</h3>
  </div>
  <div class="container">
    <div class="row">
      <div class="span12">
      <div class="thumbnail left">
        <img src="http://placehold.it/200x200" alt="">
      </div><!--/thumbnail-->
      <p class="about">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like.</p>
    </div>
  </div>
</div>

    
  </div>
</div>

app/views/mains/creative_minds.html.erb
<div class="container">
  <div class="row">
    <div class="span12 minus65">
      <h2 class="titles">the creative minds</h2>
       <h3 class="smalltitles minus20">meet the team</h3>
    </div>
  </div>
</div><!--/container-->

 <div class="container">
  <div class="row">
    <div class="span6">
     <div class="thumbnail">
      <img src="http://placehold.it/240x160" alt="">
       <h3 class="titles center">Mike</h3>
     </div><!--/thumbnail-->
     <p class="cm">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English</p>
    </div>

    <div class="span6">
     <div class="thumbnail">
      <img src="http://placehold.it/240x160" alt="">
       <h3 class="titles center">Rich</h3>
     </div><!--/thumbnail-->
     <p class="cm">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English</p>
    </div>

    <div class="span6">
     <div class="thumbnail">
      <img src="http://placehold.it/240x160" alt="">
       <h3 class="titles center">Karl</h3>
     </div><!--/thumbnail-->
     <p class="cm">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English</p>
    </div>

    <div class="span6">
      <div class="thumbnail">
      <img src="http://placehold.it/240x160" alt="">
       <h3 class="titles center">adam</h3>
     </div><!--/thumbnail-->
     <p class="cm">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English</p>
    </div>
     


    </div><!--/row-->
  </div><!--/container-->




  

app/views/mains/index.html.erb
<div class="container">
  <div class="row">
    <div class="span10 offset1">
     <%= render 'shared/flexslider' %>
      <%= render 'shared/middlesectionhome' %>
       <%= render 'shared/lowersectionhome' %>
    </div>
  </div>
</div>

app/views/mains/portfolio.html.erb
<div class="container">
 <div class="row">
  <div class="span12 minus65">
   <h1 class="titles">Our Portfolio</h1>
    <h3 class="smalltitles minus20">sample a visual delicacy</h3>
  </div>
 </div>
</div>

<div class="container">
    <div class="row">
      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/1.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>

      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/2.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>

      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/3.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>

      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/5.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>
    </div><!--row-->
    <br />

    <div class="row">
      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/1.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>

      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/6.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>

      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/7.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>

      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/8.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>
    </div><!--row-->
  </div><!--/container-->

app/views/shared/_about.html.erb
<div class="span4 minus65">
  <h1 class="titles center">about FP Studios</h1>
    <h3 class="smalltitles right minus20">you are curious then?</h3>
      <div class="thumbnail top65">
        <img src="http://placehold.it/200x200" alt="">
      </div><!--/thumbnail-->
</div>

    <div class="span8 lightborder top65">
      <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like.</p>
    </div>

app/views/shared/_flexslider.html.erb
<div class="flexslider">
      <ul class="slides">
        <li>
          <img src="/assets/tulipcoverscroll.jpg" />
          <div class="flex-caption">
            <h3>Tulip Garden</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In venenatis porttitor massa eget pretium. Mauris vel erat sem, id tempor est. Pellentesque lobortis iaculis massa quis auctor.</p>
          </div>
        </li>
        <li>
          <a href="#"><img src="/assets/frankcamerascroll.jpg" /></a>
          <div class="flex-caption">
            <h3>Frank Camera</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In venenatis porttitor massa eget pretium. Mauris vel erat sem, id tempor est. Pellentesque lobortis iaculis massa quis auctor.</p>
          </div>
        </li>
        <li>
          <img src="/assets/tulipcoverscroll.jpg"/>
          <div class="flex-caption">
            <h3>Real Recipes</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In venenatis porttitor massa eget pretium. Mauris vel erat sem, id tempor est. Pellentesque lobortis iaculis massa quis auctor.</p>
          </div>
        </li>
        <li>
          <img src="/assets/frankcamerascroll.jpg"/>
          <div class="flex-caption">
            <h3>Zombie Chase</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In venenatis porttitor massa eget pretium. Mauris vel erat sem, id tempor est. Pellentesque lobortis iaculis massa quis auctor.</p>
          </div>
        </li>
      </ul>
    </div>
  </div>
  <span id="responsiveFlag"></span>

app/views/shared/_footer.html.erb
<footer>
<div class="container">
 <div class="row">
  <div class="span6">
  <ul class="copyright">
    <li><a class="titles font20" href="#">Website built by Fishplate studios&nbsp;&copy;</a></li>
  </ul>
  </div>
  <div class="span6">
   <ul class="social-media">
    <li><a class="titles font20" href="#">Follow Us</a></li>
    <li><img src="/assets/facebook.png"></li>
    <li><img src="/assets/twitter.png"></li>
   </ul>
  </div>

 </div>
</div>
</footer>

app/views/shared/_lowersectionhome.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <h3 class="titles center">FP Studios Services</h3>
      <div class="row">
        <div class="span4">
          <h3 class="titles center">Web Design</h3>
          <p class="ostxt">We have over 20 years of web development experience and love creating new identities for our clients, we want the world to see just how great your company is.</p>

        </div><!--/div-->

        <div class="span4">
          <h3 class="titles center">Branding</h3>
          <p class="ostxt">Our graphic designers are passionate about creating the right identity for your brand, they transform imagination into a visual reality and we will work with you to showcase your business in the best possible way… and some more. As they say ‘a picture is worth a thousand words’</p>

        </div><!--/div-->

        <div class="span4">
          <h3 class="titles center">Responsive Web Design</h3>
          <p class="ostxt">There are more mobile devices in the world than desktop pcs, so why should you miss out on reaching potential customers to grow your business. We can ensure your site is available to everyone, whether it is via a desktop pc , mobile phone or tablet</p>

        </div><!--/div-->

      </div><!--/row-->
    </div>
     <div class="span6">
      <h3 class="titles center">Latest Projects</h3>
       <div class="thumbnail">
        <img src="http://placehold.it/600x250" alt="">
      </div><!--/thumbnail-->
     </div><!--/span6-->


  </div><!--/row-->
</div><!--/container-->

app/views/shared/_middlesectionhome.html.erb
<div class="container">
  <div class="row">
    <div class="span4">
      <h3 class="titles center">The Team</h3>
       <div class="row">
        <div class="span2">
          <div class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
             <h4 class="titles center">Michael Jones</h4>
              <h5 class="titles center">Graphic Designer</h5>
          </div><!--/thumbnail-->

        </div><!--/span2-->
         <div class="span2">
           <div class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
             <h4 class="titles center">Richard Lewis</h4>
             <h5 class="titles center">Web Developer</h5>
          </div><!--/thumbnail-->
        </div><!--span2-->
       </div><!--row-->

       <div class="row">
        <div class="span2">
          <div class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
            <h4 class="titles center">Karl Turner</h4>
            <h5 class="titles center">Web Developer</h5>
          </div><!--/thumbnail-->

        </div><!--/span2-->
         <div class="span2">
           <div class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
             <h4 class="titles center">Adam Jones</h4>
             <h5 class="titles center">Graphic Designer</h5>
          </div><!--/thumbnail-->
        </div><!--span2-->
       </div><!--row-->

    </div>
     <div class="span8">
      <h3 class="titles center">Curious about what we do?</h3>
       <p class="hometext">We are fishplatestudios and&nbsp;<span class="boldtext">you</span> are the reason we love what we do.&nbsp;<span class="boldtext">You</span>&nbsp;imagine and we create (with a little magic inbetween) and voila, a brand new website, branding or both.
       We have a team of professional designers and developers ready to turn your vision into a reality.<br><br>
       Everything we do is bespoke so you can rest assured that no two projects are the same.</p>
     </div>
  </div>
</div>

app/views/shared/_portfolio.html.erb
<div class="container">
 <div class="row">
  <div class="span4 minus65">
   <h1 class="titles center">Our Portfolio</h1>
    <h3 class="smalltitles right minus20">sample a visual delicacy</h3>
  </div>
 </div>
</div>

<div class="container">
    <div class="row">
      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/1.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>

      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/2.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>

      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/3.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>

      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/5.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>
    </div><!--row-->
    <br />

    <div class="row">
      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/1.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>

      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/6.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>

      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/7.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>

      <div class="span3">
        <div class="thumbnail view-seventh">
          <img src="/assets/8.jpg" alt="" />

          <div class="mask">
            <h2>Title</h2>

            <p>Your Text</p><a href="#" class="info">Read More</a>
          </div>
        </div>
      </div>
    </div><!--row-->
  </div><!--/container-->